### ISSUE TITLE
Missing 3D models mime type

### ISSUE THREAD

**Issue by Renrhaf** [thephpleague/flysystem#1179]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | master

#### Summary

The MimeType class is not able to deduce mimetype from 3D models files and associated textures.
Extensions of these files are : "glb", "gltf", "usdz", "fbx", "obj", etc
Maybe a way to extend/alter the list of extensions via events or something would be the right way ?

#### How to reproduce

Ask for mimetype using the flysystem for a file with one of these extensions.
The returned value is "text/plain".

**Comment by Renrhaf** [comment]
Something similar done in https://github.com/thephpleague/flysystem/issues/593

**Comment by GrahamCampbell** [comment]
Fixed in 2.x. ;)

**Comment by frankdejonge** [comment]
Hi @Renrhaf an event based mechanism or something like that is not likely to be added in V1, in V2 there are a lot more mime-types added and the compositional aspects allow you to add your own when needed. I know that doesn't solve your problem straight away, but you can always send a PR to add the mime types.

**Comment by Renrhaf** [comment]
Hi and thanks @frankdejonge @GrahamCampbell, closing if fixed in the new version. I'll make use of it to fix my use case. 👍

**Comment by SuperDJ** [comment]
Even in 2.x there seem to be some missing file type extensions like `.pat` and `.rfa`.
